// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY1YCnKvUplrJqEWgNDpf_QJ7kEArSokE',
    appId: '1:907390941251:web:1547cbffb5745928773cf6',
    messagingSenderId: '907390941251',
    projectId: 'newsapp-9fa78',
    authDomain: 'newsapp-9fa78.firebaseapp.com',
    storageBucket: 'newsapp-9fa78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDODG-qiF8OVDfyvGA19vNilCE9KkuMRzY',
    appId: '1:907390941251:android:2c03922ce1fcb9fe773cf6',
    messagingSenderId: '907390941251',
    projectId: 'newsapp-9fa78',
    storageBucket: 'newsapp-9fa78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQNjqbHjt5fiVsUtFYu7NdCy_WgNjsbc',
    appId: '1:907390941251:ios:0f681e698c862658773cf6',
    messagingSenderId: '907390941251',
    projectId: 'newsapp-9fa78',
    storageBucket: 'newsapp-9fa78.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQNjqbHjt5fiVsUtFYu7NdCy_WgNjsbc',
    appId: '1:907390941251:ios:9041d981efebc3e1773cf6',
    messagingSenderId: '907390941251',
    projectId: 'newsapp-9fa78',
    storageBucket: 'newsapp-9fa78.appspot.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
